#pragma once
#include <Arduino.h>
#include "version.h"

// Web UI (HTML/CSS/JS) — tabbed layout (Operate / NFC / Setup / System), slate+cyan,
// light/dark-aware. Served as a PROGMEM string via server.send_P().
static const char INDEX_HTML[] PROGMEM =
    "<!DOCTYPE html><html lang='en'><head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'/>"
    "<title>OctoScale</title>"
    // Favicon: the OctoScale octopus head, cropped square from assets/octoscale_logo.jpeg
    // and recolored to a transparent background (same near-white threshold approach as
    // display.h's displayLogoThemed, applied offline during generation). Inlined as a
    // base64 data: URI (1.6 KB) rather than a separate file/endpoint -- this project has
    // no filesystem/SPIFFS for static assets, everything is served from PROGMEM strings,
    // same as OctoLogo.h's TFT bitmap.
    "<link rel='icon' type='image/png' href='data:image/png;base64,"
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAGR0lEQVR42q1XXWwc1RX+zrkzs7+24zibH8c2dZNGJSaI0PSPBsWBF6hEpararcpDoVJVpIJaIQWpPKAlVSMkUJEQ6kv7BlUfdpU8VEWqQlEchBEgiBCRzU8CxDEBN44Te+2d2fm59/RhvMt6d71xClda3dk7d875zv85hKZVFOGjRMYB8MzZM0devzxf/HCpkmYQkwCGNEAMwtolIoAATASQQAQiTHJgS27xzh0Dv/nlrn3HV+8REUnzt1x/yJdK6iiREZGBhydP//PE558988HiUpYBFhgYNgAIMfX4V19EFL8iQEAAEZEBvzF/ZfML5z8t//GdN/8iIkkikmKxyG0AisUilwsFPT9fHfz16VdOT7refVerNW1xTJiIQKB4b/o1r9b/ICABkbkVT05WKr99dPLVEyKSObqqiQYAEaHVw/7Hp954+W3PHQsqldAmUoKvtgxASWZeWlgIX3NX7n3ircl/p44dMwRQHYSaHhtTHz7yiJm76+CL70XhIb3ihsxki0i7VOtJ2+W9ALCYVVDzwzmlRh94+CGa2DlyanpsTE2XyzGKp958/acnlysn5hevRY5SFkAbkpCIGr6w3nPjrojUDJldfT3qsbFbD9w5OHimVCoxi0jvu4uLTy9UXbGJWXB96eoSNjNpZdiqCQOQw4KLoY+/f3T2mAJkampKrOfPnvnFZUW7JQo0iBVEgC4qvh6j5jt1M9Z3Eijfq8kMy12vzJ7/1vjw7nM8dW3xwUXXE4uYNmLfbqvZBJ0ACwGKoKt20n7pwqWfA4A1W63eHkWabIDwfzJfTyudzhUxVYMQFyJzkAHwQs1zGAJZh9DXAaYlPVAUBPBNeIsWybIvZqNOv+HIuN4ViMDXpvfcwsIm1mCg7iRfwf6dvl2HHokxAHFqzvM2M4sBgbp6d7fUW3/X7PHSoV7UzSOAgBladEDGrDAZiu3fxZ6dis96tm4G2gyyaRdihk3W8sGRkaucdawG8xtxwmbJW4G2Jqo2QZiQUDwPoMJbM5mKicui3KgPdIr7DSAXZTM2OTytmA1vc1Jv2U4itk07h46aaTVJa+FqSNxCkohgjJE0O7gp0zdpRMB7cn0v9TgKevV2g7AAtNqA3Gj8CwAWgIVawAq0iOrTou/ZNfoyAPBDN992fICkGkEUGZEvJQJqrodI6w2pOPZwAURggxDVfPiu2wAUgyCtkkkMJ513x7cNvw8R4izR7HAy9Y9kTw80oCECVozFq9dw4dx5zH08A/HDjdlZACZGbaWKix9/itlPZhC4XtwrAoiMxqZUknYP9D/na43ixIRiA+DHQ0PPbhWJdKw5IQFqy1WwAXy3iitXLmO1Vq0bgo1WzQj+e2kOURhBIo2g5sffihitFG/TZvbILbcfB0BPjo9rzpdK6t7Rb3+w23FOOOkUC8gAhEQiERO0LLhLywj9oKPDNTssM8NzXXieC1YKRATLtgEBQhNJLt1LP9iy/c9E5JZEmIiE86tN4q/27X9yh0V+SAQiSLI3A6G4k9ChQVQL4oxppKP9jQhAgOd5EInPLNtCMp0CRAw5Sf4G45NH9+//K4pFzgMGALhQKOh8uczf2bLl/VtT2af6e7Mq0FqnMxlke3oQBSGMNg0GcWBI92gwBjqK0DuwGZZtwzeRbM9k6PDI8O+JyMuPjTXmA2oMDOUySz6v7v/PybenfW+fFYZGByF/MfMZLNvC1puG1jBh5rYQZGYEXg1zM7NIZ7LI7dyB0EjkZFPWHalU+flDdxd+JiVVpoJeMxcQkeTjPfjJ0ODvtjuO+AaiHBs793wT20aHO+b4TmnZTiQwvGcXckM7IDCimXjUspeK3/3hESOgvch3nozKhYI+dOqUdf/N+yb2OIkX0tm0ioyJIAIxHSahdSMxzmiR0QglMv19Gb6tb9MfNqfTF0uIR7+OAABgfHzcCECPff+OP+1U7GpArQ50bZXtetmQiIxyUmqQ8N7jB773t3yppApYy7wNwFEiky+VeCSVOr/dTvwrkU6TEdHNVa5bK76mDReYdCqJvdn+F4lI783lCNReb7j14HIuRwDIIucjpRRMh4LSrQrWtWVgSAHoTziXuiXPNgCnDx/WIkIhgnt834eqp8Ab6PtEBAosNa0xs1z5EQBMTEx0vPs/HyWGh8UJCZYAAAAASUVORK5CYII=' />"
    "<style>"
    // --- tokens: matches the TFT menu palette exactly (menu.h menuApplyTheme) so the
    // web UI and the on-device display read as the same product in either theme.
    // Light = TFT light theme (white bg, cyan accent), dark = TFT dark theme (black
    // bg, amber accent). ok/warn/bad map to MENU_OK/MENU_WARN/MENU_ERR (theme-fixed).
    ":root{--bg:#ffffff;--surface:#f7f7f7;--surface2:#efefef;--line:#c5c2c5;"
    "--ink:#202420;--muted:#626562;--accent:#00beff;--accent-ink:#00232a;"
    "--ok:#20ca41;--warn:#c56100;--bad:#ee1c20}"
    "@media(prefers-color-scheme:dark){:root:not([data-theme='light']){"
    "--bg:#000000;--surface:#161616;--surface2:#1f1f1f;--line:#393839;"
    "--ink:#e6e2e6;--muted:#acaeac;--accent:#ffa500;--accent-ink:#2a1800;"
    "--ok:#20ca41;--warn:#c56100;--bad:#ee1c20}}"
    ":root[data-theme='dark']{--bg:#000000;--surface:#161616;--surface2:#1f1f1f;"
    "--line:#393839;--ink:#e6e2e6;--muted:#acaeac;--accent:#ffa500;"
    "--accent-ink:#2a1800;--ok:#20ca41;--warn:#c56100;--bad:#ee1c20}"
    "*{box-sizing:border-box}"
    "body{margin:0;background:var(--bg);color:var(--ink);"
    "font:15px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;-webkit-font-smoothing:antialiased}"
    ".mono{font-family:ui-monospace,'SF Mono',Menlo,monospace;font-variant-numeric:tabular-nums}"
    ".wrap{max-width:720px;margin:0 auto;padding:0 14px 40px}"
    // --- header + status + tabs ---
    "header{position:sticky;top:0;z-index:10;background:var(--bg);border-bottom:1px solid var(--line);overflow:hidden}"
    ".brand{display:flex;align-items:center;gap:9px;padding:13px 2px 9px}"
    ".brand .bd{width:10px;height:10px;border-radius:50%;background:var(--accent)}"
    ".brand h1{font-size:17px;margin:0;font-weight:650}"
    ".brand .ver{font-size:12px;color:var(--muted);margin-left:auto}"
    ".themebtn{appearance:none;background:var(--surface2);border:1px solid var(--line);"
    "color:var(--muted);cursor:pointer;border-radius:7px;padding:0;font:inherit;font-size:15px;"
    "margin-left:8px;width:30px;height:26px;line-height:24px;text-align:center;flex:0 0 auto}"
    ".status{display:flex;gap:7px;flex-wrap:wrap;padding:0 2px 9px}"
    ".chip{display:inline-flex;align-items:center;gap:6px;font-size:12px;padding:4px 9px;"
    "border-radius:999px;background:var(--surface2);border:1px solid var(--line);color:var(--muted)}"
    ".chip b{color:var(--ink);font-weight:600}"
    ".chip .led{width:7px;height:7px;border-radius:50%;background:var(--muted)}"
    ".led.ok{background:var(--ok)}.led.warn{background:var(--warn)}.led.bad{background:var(--bad)}"
    "nav{display:flex;gap:2px}"
    "nav button{appearance:none;border:0;background:none;cursor:pointer;font:inherit;font-size:14px;"
    "font-weight:550;color:var(--muted);padding:9px 14px 11px;border-bottom:2px solid transparent;"
    "white-space:nowrap;margin-bottom:-1px;width:auto}"
    "nav button:hover{color:var(--ink)}"
    "nav button[aria-selected='true']{color:var(--accent);border-bottom-color:var(--accent)}"
    "nav button:focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:4px}"
    // --- panels + cards ---
    "main{padding-top:16px}"
    ".panel{display:none}.panel.active{display:block}"
    ".grid{display:grid;gap:12px}"
    "@media(min-width:600px){.grid.two{grid-template-columns:1fr 1fr}}"
    ".card{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:15px}"
    ".card.span{grid-column:1/-1}"
    ".card h2{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);"
    "margin:0 0 11px;font-weight:650}"
    ".card h2 .hint{text-transform:none;letter-spacing:0;font-weight:500;float:right;color:var(--muted)}"
    ".big{font-size:38px;font-weight:600;line-height:1}.big small{font-size:16px;color:var(--muted);font-weight:500}"
    // rows (key/value)
    ".row{display:flex;justify-content:space-between;gap:10px;padding:6px 0;border-bottom:1px solid var(--line);font-size:14px}"
    ".row:last-child{border-bottom:0}.row .k{color:var(--muted)}.row .v{text-align:right}"
    // form controls
    "label.field{display:block;font-size:13px;color:var(--muted);margin:11px 0 5px}"
    "input[type=text],input[type=number],input[type=password],input[type=url],select{"
    "width:100%;padding:9px 11px;font:inherit;color:var(--ink);background:var(--surface2);"
    "border:1px solid var(--line);border-radius:7px;margin:0}"
    "input:focus,select:focus{outline:2px solid var(--accent);outline-offset:-1px;border-color:var(--accent)}"
    "input[type=file]{width:100%;font-size:13px;color:var(--muted)}"
    // buttons
    "button{appearance:none;cursor:pointer;font:inherit;font-weight:600;font-size:14px;padding:9px 15px;"
    "border-radius:7px;border:1px solid var(--line);background:var(--surface2);color:var(--ink);"
    "margin-top:10px;width:100%;transition:filter .12s,transform .05s}"
    "button:hover{border-color:var(--accent)}"
    "button:active{transform:scale(.99)}"
    "button:disabled{opacity:.6;cursor:progress}"
    "button.primary{background:var(--accent);color:var(--accent-ink);border-color:var(--accent)}"
    "button.primary:hover{filter:brightness(1.06)}"
    "button.ghost{background:var(--surface2)}"
    "button.danger{color:var(--bad);border-color:color-mix(in srgb,var(--bad) 40%,var(--line))}"
    "button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}"
    ".btns{display:flex;gap:8px;flex-wrap:wrap}.btns button{width:auto;flex:1}"
    // callout (neutral bg + colored rail on the left)
    ".msg{padding:11px 13px;border-radius:6px;font-size:14px;background:var(--surface2);"
    "border:1px solid var(--line);border-left:3px solid var(--muted);margin:0 0 4px}"
    ".msg h4{margin:0 0 5px;font-size:13px}.msg.S{border-left-color:var(--ok)}"
    ".msg.ok{border-left-color:var(--ok)}.msg.warn{border-left-color:var(--warn)}.msg.bad{border-left-color:var(--bad)}"
    // progress bars (weigh/timer/system) — padding:0 keeps the fill visible
    ".bar{padding:0;height:8px;border-radius:5px;background:var(--surface2);overflow:hidden;border:1px solid var(--line)}"
    ".bar>i{display:block;height:100%;background:var(--accent)}"
    // printer cards (JS-generated), styled from tokens
    ".pcard{background:var(--surface2);border:1px solid var(--line);border-radius:7px;padding:10px 12px;margin:8px 0}"
    ".pcard .top{display:flex;align-items:center;gap:8px}"
    ".pcard .nm{font-weight:650;flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    ".pcard .addr{color:var(--muted);font-size:.85em;margin:2px 0}"
    ".pcard .db{font-size:.8em;color:var(--muted);margin-top:2px}"
    ".pcard .act{display:flex;gap:6px;margin-top:8px}"
    ".pcard .act button{flex:1;margin-top:0;padding:6px 10px;font-size:.9rem}"
    ".pcard .act button.del{color:var(--bad);border-color:color-mix(in srgb,var(--bad) 40%,var(--line))}"
    ".pcard .edit{margin-top:8px;padding-top:8px;border-top:1px solid var(--line)}"
    ".pcard .edit input{margin-top:6px}"
    ".dot{width:9px;height:9px;border-radius:50%;background:var(--muted);flex:0 0 auto;display:inline-block}"
    ".dot.ok{background:var(--ok)}.dot.err{background:var(--bad)}.dot.wait{background:var(--warn)}"
    ".pst{font-size:.82em;color:var(--muted)}"
    ".switch{display:flex;align-items:center;gap:10px;cursor:pointer;user-select:none}"
    ".switch input{width:auto;margin:0}"
    ".note{font-size:12px;color:var(--muted);margin-top:8px}"
    ".hidden{display:none}"
    // Spool info card (2x2 grid): left vendor/material + 'remaining', right color + weight.
    ".spoolcard{display:grid;grid-template-columns:1fr auto;gap:6px 14px;align-items:center;"
    "margin:10px 0;padding:12px 14px;border:1px solid var(--line);border-radius:10px;background:var(--surface2)}"
    ".sc-vend{font-weight:600;font-size:1.05em}"
    ".sc-mat{font-size:.9em;color:var(--muted)}"
    ".sc-tr{display:flex;align-items:center;gap:8px;justify-self:end}"
    ".sc-cn{font-size:.95em}"
    ".swatch{width:22px;height:22px;border-radius:5px;border:1px solid var(--line);"
    "display:inline-block;flex:0 0 auto;box-shadow:inset 0 0 0 1px rgba(0,0,0,.15)}"
    ".sc-bl{color:var(--muted);font-size:.85em;text-transform:uppercase;letter-spacing:.04em}"
    ".sc-br{justify-self:end;font-weight:700;font-size:1.35em;color:var(--accent);"
    "font-variant-numeric:tabular-nums}"
    "</style></head><body>"
    "<header><div class='wrap' style='padding-bottom:0'>"
    "<div class='brand'><span class='bd'></span><h1>OctoScale</h1>"
    "<button class='themebtn' onclick='toggleTheme()' title='Toggle theme'>&#9681;</button>"
    "</div>"   // version moved out of the header (already shown in the footer)
    // Device status bar (always visible) — order matches the display footer.
    "<div class='status'>"
    "<span class='chip' id='cNfc'><span class='led'></span>NFC</span>"
    "<span class='chip' id='cScale'><span class='led'></span>Scale</span>"
    "<span class='chip' id='cDb'><span class='led'></span>DB</span>"
    "<span class='chip' id='cWifi'><span class='led'></span>WiFi <b>--</b></span></div>"
    // Tabs
    "<nav role='tablist'>"
    "<button role='tab' aria-selected='true' onclick=\"tab(this,'betrieb')\">Operate</button>"
    "<button role='tab' aria-selected='false' onclick=\"tab(this,'nfc')\">NFC</button>"
    "<button role='tab' aria-selected='false' onclick=\"tab(this,'scale')\">Scale</button>"
    "<button role='tab' aria-selected='false' onclick=\"tab(this,'setup')\">Setup</button>"
    "<button role='tab' aria-selected='false' onclick=\"tab(this,'system')\">System</button>"
    "<button role='tab' aria-selected='false' onclick=\"tab(this,'debug')\">Debug</button>"
    "</nav></div></header>"
    "<main class='wrap'>"

    // ================= OPERATE =================
    "<section id='betrieb' class='panel active'><div class='grid two'>"
    // Spool-loading flow (polls /flow/status). Hidden when idle.
    "<div class='card span' id='flowcard' style='display:none'>"
    "<h2><span id='fh'>Load spool</span></h2>"
    "<div id='ftbar' class='bar' style='display:none;margin-bottom:10px'>"
    "<i id='ftfill' style='width:100%;transition:width .8s linear,background .3s'></i></div>"
    "<div id='fbody'></div>"
    "<button id='fcancel' class='ghost' style='display:none' onclick='fcancel()'>Cancel</button>"
    "</div>"
    // Weight
    "<div class='card'><h2>Weight</h2>"
    "<div class='big mono'><span id='w'>--</span><small> g</small></div>"
    "<form onsubmit=\"fetch('/tare');return false\"><button type='submit' class='ghost'>Tare</button></form></div>"
    // Short status / hint
    "<div class='card'><h2>Hint</h2>"
    "<div class='msg'>Place a spool with an NFC tag &ndash; the load flow appears here automatically.</div></div>"
    "</div></section>"

    // ================= NFC =================
    // Left column: Tag on reader / Write ID / Erase, stacked. Right column: NFC debug,
    // spanning that same height. A nested grid (not the outer 'grid two') is needed --
    // a plain 2-col grid fills row by row in document order, which would put "Erase"
    // and "NFC debug" side by side on row 2 instead of all three left cards stacking
    // with debug alongside them.
    "<section id='nfc' class='panel'><div class='grid two'>"
    "<div class='grid' style='gap:12px;align-content:start'>"
    "<div class='card'><h2>Tag on reader</h2>"
    "<div class='row'><span class='k'>UID</span><span class='v mono' id='uid'>--</span></div>"
    "<div class='row'><span class='k'>Data (page 4)</span><span class='v mono' id='tag'>--</span></div></div>"
    "<div class='card'><h2>Write ID to tag</h2>"
    "<form onsubmit=\"nfcwid();return false\">"
    "<label class='field'>Spool database ID</label>"
    "<input type='number' id='nid' min='0' placeholder='Spool DB ID'>"
    "<button type='submit' class='primary'>Write to tag</button></form>"
    "<p class='note'>NFC-V (ISO15693), NFC-A/NTAG, and Mifare Classic (factory key only).</p></div>"
    "<div class='card'><h2>Erase tag</h2>"
    "<div class='msg'>Wipes the spool ID and all Extended data (material, color, "
    "weights, ...) from the tag on the reader. Cannot be undone.</div>"
    "<button onclick='nfcerase()' class='danger'>Erase tag</button>"
    "<p class='note'>On NTAG/NFC-V OpenSpool or OpenPrintTag tags the NDEF content is "
    "cleared, but the tag's write-once Capability Container stays set (a hardware "
    "limit, not reversible by any writer) &ndash; the tag still reads as blank/empty "
    "either way.</p></div>"
    "</div>"
    "<div class='card'><h2>NFC debug <span class='hint'>read-only, show tag type</span></h2>"
    "<label class='switch'><input type='checkbox' id='ndbg' onchange='ndbgset(this)'>"
    "<span>Debug mode active</span></label>"
    "<div class='msg' id='ndbox' style='display:none;margin-top:12px'>"
    "<div class='row'><span class='k'>Type</span><span class='v' id='ndtype'>--</span></div>"
    "<div class='row'><span class='k'>UID</span><span class='v mono' id='nduid'>--</span></div>"
    "<div class='row' id='ndarow' style='display:none'><span class='k'>ATQA / SAK</span>"
    "<span class='v mono'><span id='ndatqa'>--</span> / <span id='ndsak'>--</span></span></div>"
    "<div class='row' id='ndprow' style='display:none'><span class='k'>Product</span>"
    "<span class='v' id='ndprod'>--</span></div>"
    "<div class='row' id='ndvrow' style='display:none'><span class='k'>Memory layout</span>"
    "<span class='v mono' id='ndblk'>--</span></div>"
    "<div class='row' id='ndvirow' style='display:none'><span class='k'>DSFID / AFI</span>"
    "<span class='v mono'><span id='nddsfid'>--</span> / <span id='ndafi'>--</span></span></div>"
    "<div class='row' id='ndicrow' style='display:none'><span class='k'>IC reference"
    "<span class='hint'> (raw, not decoded to a chip name)</span></span>"
    "<span class='v mono' id='ndicref'>--</span></div>"
    "<div class='row' id='ndccrow' style='display:none'><span class='k'>NDEF bit</span>"
    "<span class='v' id='ndcc'>--</span></div>"
    "<div class='row' id='ndfrow' style='display:none'><span class='k'>Format</span>"
    "<span class='v' id='ndfmt'>--</span></div>"
    "<div class='row' id='ndcaprow' style='display:none'><span class='k'>Useable capacity</span>"
    "<span class='v mono' id='ndcap'>--</span></div>"
    "<div id='ndext' style='display:none;margin-top:10px;padding-top:10px;"
    "border-top:1px solid var(--line)'>"
    "<div class='row'><span class='k'>Database ID</span><span class='v mono' id='nedbid'>--</span></div>"
    "<div class='row'><span class='k'>Material</span><span class='v' id='nemat'>--</span></div>"
    "<div class='row'><span class='k'>Vendor</span><span class='v' id='nevnd'>--</span></div>"
    "<div class='row'><span class='k'>Color</span><span class='v' id='necol'>--</span></div>"
    "<div class='row'><span class='k'>Color name</span><span class='v' id='necoln'>--</span></div>"
    "<div class='row'><span class='k'>Diameter</span><span class='v mono' id='nedia'>--</span></div>"
    "<div class='row'><span class='k'>Density</span><span class='v mono' id='neden'>--</span></div>"
    "<div class='row'><span class='k'>Total weight</span><span class='v mono' id='netw'>--</span></div>"
    "<div class='row'><span class='k'>Spool weight</span><span class='v mono' id='nesw'>--</span></div>"
    "<div class='row'><span class='k'>Used weight</span><span class='v mono' id='neuw'>--</span></div>"
    "<div class='row'><span class='k'>Temperature</span><span class='v mono' id='netemp'>--</span></div>"
    "<div class='row' id='netrgrow' style='display:none'><span class='k'>Temp range</span><span class='v mono' id='netrg'>--</span></div>"
    "<div class='row'><span class='k'>Bed temperature</span><span class='v mono' id='nebtemp'>--</span></div>"
    "<div class='row' id='nebtrgrow' style='display:none'><span class='k'>Bed temp range</span><span class='v mono' id='nebtrg'>--</span></div>"
    "<div class='row'><span class='k'>Enclosure temperature</span><span class='v mono' id='netemp2'>--</span></div>"
    "<div class='row'><span class='k'>Display name</span><span class='v' id='nedn'>--</span></div>"
    "<div class='row'><span class='k'>Remaining weight</span><span class='v mono' id='nerw'>--</span></div>"
    "<div class='row'><span class='k'>Total length</span><span class='v mono' id='netl'>--</span></div>"
    "<div class='row'><span class='k'>Used length</span><span class='v mono' id='neul'>--</span></div>"
    "<div class='row'><span class='k'>Code</span><span class='v' id='necode'>--</span></div>"
    "<div class='row'><span class='k'>Batch number</span><span class='v' id='nebatch'>--</span></div>"
    "<div class='row'><span class='k'>Finish</span><span class='v' id='nefin'>--</span></div>"
    "<div class='row'><span class='k'>Purchased from</span><span class='v' id='nepf'>--</span></div>"
    "<div class='row'><span class='k'>Purchased on</span><span class='v mono' id='nepo'>--</span></div>"
    "<div class='row'><span class='k'>Cost</span><span class='v mono' id='necost'>--</span></div>"
    "<div class='row'><span class='k'>First use</span><span class='v mono' id='nefu'>--</span></div>"
    "<div class='row'><span class='k'>Last use</span><span class='v mono' id='nelu'>--</span></div>"
    "</div>"
    // Unknown-tag fallback: no OctoScale/OpenSpool/OpenPrintTag data recognized, but a
    // tag IS present. Offers a raw sector/block dump instead of just showing blanks --
    // useful for identifying a foreign/vendor-written tag (see menu.h's matching "See
    // dump in web UI" TFT hint). Mifare Classic only for now (see /nfcdump).
    "<div id='ndunk' style='display:none;margin-top:10px;padding-top:10px;"
    "border-top:1px solid var(--line)'>"
    "<div class='msg'>No known OctoScale/OpenSpool/OpenPrintTag data found on this tag. "
    "It may be blank, or written by something else (a vendor tool, another app).</div>"
    "<button onclick='nfcdump()' class='primary' id='ndumpbtn' style='margin-top:8px'>Create dump</button>"
    "<div id='ndumpout' style='display:none;margin-top:10px'>"
    "<div class='row'><span class='k'>Result</span><span class='v' id='ndumpmsg'>--</span></div>"
    "<div style='overflow-x:auto;margin-top:8px'>"
    "<table class='mono' style='width:100%;border-collapse:collapse;font-size:12px' id='ndumptbl'></table>"
    "</div></div>"
    "</div>"
    "</div>"
    "</div>"
    // Chip-level health/diagnostic status (PN5180 itself, not the tag on it) -- only
    // populated while NFC debug is on (see /nfcprobe's "chip" object); double-width,
    // below the other NFC cards.
    "<div class='card span' id='ndchipcard' style='display:none'><h2>PN5180 chip status "
    "<span class='hint'>reader hardware, not the tag</span></h2>"
    "<div class='grid two' style='gap:4px 24px'>"
    "<div class='row'><span class='k'>Die ID</span><span class='v mono' id='ndcdie' style='font-size:11px'>--</span></div>"
    "<div class='row'><span class='k'>EEPROM layout</span><span class='v mono' id='ndceev'>--</span></div>"
    "<div class='row'><span class='k'>RF field</span><span class='v' id='ndcrf'>--</span></div>"
    "<div class='row'><span class='k'>Transceiver state</span><span class='v mono' id='ndcts'>--</span></div>"
    "<div class='row'><span class='k'>System mode</span><span class='v mono' id='ndcsm'>--</span></div>"
    "<div class='row'><span class='k'>System status</span><span class='v mono' id='ndcss'>--</span></div>"
    "<div class='row'><span class='k'>Overtemp warning</span><span class='v' id='ndcot'>--</span></div>"
    "<div class='row'><span class='k'>Temp control</span><span class='v mono' id='ndctc'>--</span></div>"
    "<div class='row'><span class='k'>IRQ status</span><span class='v mono' id='ndcirq'>--</span></div>"
    "</div></div>"
    "</div></section>"

    // ================= SCALE =================
    "<section id='scale' class='panel'><div class='grid two'>"
    "<div class='card'><h2>Scale calibration</h2>"
    "<div class='row'><span class='k'>Current factor</span><span class='v mono' id='f'>--</span></div>"
    "<form onsubmit=\"fetch('/tare');return false\" style='margin:10px 0'>"
    "<button type='submit' class='ghost'>Tare (do this first, scale empty)</button></form>"
    "<label class='field'>Method</label>"
    "<select id='calMethod' onchange='calMethodShow()'>"
    "<option value='1'>1-point (quick)</option>"
    "<option value='2'>2-point (checks linearity, more accurate)</option></select>"
    // ---- 1-point ----
    "<div id='cal1box' style='margin-top:12px'>"
    "<div class='msg'>Place a known weight, enter its actual weight (g), calibrate.</div>"
    "<form onsubmit=\"cal();return false\">"
    "<label class='field'>Reference weight</label>"
    "<input type='number' id='cw' step='0.1' min='0' placeholder='actual weight in g'>"
    "<button type='submit' class='primary'>Calibrate</button></form></div>"
    // ---- 2-point ----
    "<div id='cal2box' style='display:none;margin-top:12px'>"
    "<div class='msg'>Uses a light and a heavy reference weight instead of one, which "
    "corrects the scale's slope more accurately across the full range (e.g. an empty vs. "
    "a full spool).</div>"
    "<div id='c2step1'>"
    "<label class='field'>Point A &ndash; light weight (g)</label>"
    "<input type='number' id='c2w1' step='0.1' min='0' placeholder='e.g. 100'>"
    "<button onclick='cal2measure(1)' class='ghost'>Place it, then measure A</button>"
    "<div id='c2msg1' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "<div id='c2step2' style='display:none'>"
    "<label class='field'>Point B &ndash; heavy weight (g)</label>"
    "<input type='number' id='c2w2' step='0.1' min='0' placeholder='e.g. 2000'>"
    "<button onclick='cal2measure(2)' class='ghost'>Place it, then measure B</button>"
    "<div id='c2msg2' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "<div id='c2step3' style='display:none;margin-top:8px'>"
    "<button onclick='cal2finish()' class='primary'>Compute &amp; save factor</button></div>"
    "<div id='c2msg3' class='note' style='text-align:center;min-height:1.1em'></div></div></div>"
    // HX711 diagnostics -- the load cell amplifier has no status registers, so this is
    // the raw ADC reading + a computed noise estimate, not chip-reported health (unlike
    // the PN5180 chip status card in the NFC tab).
    "<div class='card'><h2>HX711 diagnostics <span class='hint'>raw ADC, not chip-reported</span></h2>"
    "<div class='row'><span class='k'>HX711 responding</span><span class='v' id='scready'>--</span></div>"
    "<div class='row'><span class='k'>Last read</span><span class='v mono' id='scage'>--</span></div>"
    "<div class='row'><span class='k'>Raw ADC value</span><span class='v mono' id='scraw'>--</span></div>"
    "<div class='row'><span class='k'>Tare offset</span><span class='v mono' id='scoff'>--</span></div>"
    "<div class='row'><span class='k'>Scale factor</span><span class='v mono' id='scfac'>--</span></div>"
    "<div class='row'><span class='k'>Noise (std dev)</span><span class='v mono' id='scnoise'>--</span></div>"
    "</div>"
    "</div></section>"

    // ================= SETUP =================
    "<section id='setup' class='panel'><div class='grid two'>"
    "<div class='card span'><h2>OctoPrint printers</h2>"
    "<div id='octobox'>Loading...</div>"
    "<form onsubmit=\"octoadd();return false\">"
    "<label class='field'>Add a printer</label>"
    "<div class='grid two' style='gap:8px'>"
    "<input type='text' id='oname' placeholder='Name (e.g. Prusa MK4)'>"
    "<input type='text' id='ohost' placeholder='IP / hostname'>"
    "<input type='number' id='oport' value='80' placeholder='Port'>"
    "<input type='text' id='okey' placeholder='API key'></div>"
    "<button type='submit' class='primary'>Add printer</button></form>"
    "<button onclick='dbrefresh(event)' class='ghost'>Refresh DB info</button></div>"
    "<div class='card'><h2>Spool database</h2>"
    "<div class='msg'>Spools come from SpoolManagerExtended. Pick the preferred "
    "OctoPrint instance as the DB source. If it is offline, another instance with a "
    "<b>shared external DB</b> (&#x1F5C4;&#xFE0F;) takes over. Local SQLite "
    "(&#x1F4BE;) has no fallback.</div>"
    "<label class='field'>DB source</label>"
    "<select id='dbsel' onchange='dbset()'></select>"
    "<form onsubmit=\"dbtest(event);return false\">"
    "<label class='field'>Test: look up spool ID</label>"
    "<input type='number' id='dbtid' min='0' placeholder='Spool ID (default: tag on reader)'>"
    "<button type='submit' class='ghost'>Test</button></form>"
    "<div id='mtestmsg' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "<div class='card'><h2>Selection timeout</h2>"
    "<div class='msg'>How long the selection stays open after the <b>tag is removed</b> "
    "before it resets. <b>0 = never</b>.</div>"
    "<form onsubmit=\"tmset(event);return false\">"
    "<label class='field'>Seconds (0-60)</label>"
    "<input type='number' id='tmsec' min='0' max='60' placeholder='Seconds'>"
    "<button type='submit' class='primary'>Save timeout</button></form>"
    "<div id='tmmsg' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "</div></section>"

    // ================= SYSTEM =================
    "<section id='system' class='panel'><div class='grid two'>"
    "<div class='card'><h2>Display</h2>"
    "<div class='msg'>The screen runs at the active brightness while in use, and drops to "
    "the idle brightness after the timeout with no activity (encoder, weight, NFC).</div>"
    "<label class='field'>Active brightness: <span id='blval'>255</span> / 255</label>"
    "<input type='range' id='blv' min='10' max='255' value='255' oninput='blset(this.value)' onchange='blsave()' style='width:100%'>"
    "<label class='field'>Idle brightness: <span id='bldval'>40</span> / 255</label>"
    "<input type='range' id='bld' min='0' max='255' value='40' oninput='document.getElementById(\"bldval\").textContent=this.value' onchange='blsave()' style='width:100%'>"
    "<label class='field'>Idle timeout (seconds, 0 = never dim)</label>"
    "<input type='number' id='blt' min='0' max='3600' value='30' onchange='blsave()'>"
    "<label class='switch' style='margin-top:10px'><input type='checkbox' id='sse' onchange='blsave()'> "
    "Logo screensaver</label>"
    "<label class='field'>Screensaver after (seconds)</label>"
    "<input type='number' id='sst' min='5' max='3600' value='60' onchange='blsave()'>"
    "<div id='blmsg' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    // ---- Buzzer ----
    "<div class='card'><h2>Buzzer</h2>"
    "<div class='msg'>Signal tones on NFC read, spool load and errors. Master on/off is also "
    "in the device menu on the display. Volume and frequency apply to a passive buzzer only "
    "(an active buzzer has a fixed built-in tone).</div>"
    "<label class='switch'><input type='checkbox' id='bze' onchange='bzsave()'> Enabled</label>"
    "<label class='field'>Type</label>"
    "<select id='bzm' onchange='bzsave()'>"
    "<option value='0'>Active (on/off, fixed tone)</option>"
    "<option value='1'>Passive (PWM tone)</option></select>"
    "<label class='field'>Volume (passive only): <span id='bzvval'>200</span> / 255</label>"
    "<input type='range' id='bzv' min='0' max='255' value='200' oninput='document.getElementById(\"bzvval\").textContent=this.value' onchange='bzsave()' style='width:100%'>"
    "<label class='field'>Frequency (passive only, Hz)</label>"
    "<input type='number' id='bzf' min='100' max='8000' value='2700' onchange='bzsave()'>"
    "<button onclick='bztest(event)' class='ghost'>Test tone</button>"
    "<div id='bzmsg' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "<div class='card'><h2>System</h2><div id='sysbox'>Loading...</div></div>"
    "<div class='card'><h2>WiFi</h2><div id='wifibox'>Loading...</div>"
    "<button onclick='wifiportal(event)' class='ghost'>Reconfigure WiFi</button></div>"
    "<div class='card'><h2>Firmware update</h2>"
    "<form method='POST' action='/update' enctype='multipart/form-data'>"
    "<label class='field'>From file</label>"
    "<input type='file' name='firmware' accept='.bin,application/octet-stream'>"
    "<button type='submit' class='primary'>Update (file)</button></form>"
    "<form onsubmit=\"fwurl(event);return false\">"
    "<label class='field'>From URL (ESP downloads the .bin)</label>"
    "<input type='url' id='fwu' placeholder='http://.../firmware.bin'>"
    "<button type='submit' class='ghost'>Update from URL</button></form>"
    "<div id='fwmsg' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "<div class='card'><h2>Backup &amp; restore</h2>"
    "<div class='msg'>Saves the config. With a <b>password</b> the API keys are "
    "AES-256 encrypted &#x1F510; &ndash; without a password they are <b>omitted</b>. "
    "Restoring needs the same password.</div>"
    "<label class='field'>Password (for API keys)</label>"
    "<input type='password' id='bkpw' placeholder='Password'>"
    "<button onclick='bkexport(event)' class='ghost'>&#x1F4BE; Download backup</button>"
    "<label class='field'>Restore</label>"
    "<input type='file' id='bkfile' accept='.json,application/json'>"
    "<button onclick='bkimport(event)' class='danger'>&#x26A0;&#xFE0F; Restore (overwrites)</button>"
    "<div id='bkmsg' class='note' style='text-align:center;min-height:1.1em'></div></div>"
    "</div></section>"

    // ================= DEBUG =================
    "<section id='debug' class='panel'><div class='grid two'>"
    // ---- TFT screen preview -- double-width, first card in this tab ----
    "<div class='card span'><h2>TFT screen preview <span class='hint'>read-only, for checking layouts</span></h2>"
    "<div class='msg'>Steps through every screen the display can show, using demo data "
    "&ndash; no tag placed, no printer/DB call, nothing written. The status LED and "
    "buzzer fire in sync with whatever the real screen would trigger (buzzer stays "
    "silent if it's disabled below). On the device: turn the knob to move through "
    "screens, press it to stop.</div>"
    "<label class='switch'><input type='checkbox' id='mpv' onchange='mpvset(this)'>"
    "<span>Preview active</span></label>"
    "<label class='switch' style='margin-top:8px'>"
    "<input type='checkbox' id='mpvauto' disabled onchange='mpvAutoToggle()'>"
    "<span>Auto-cycle through screens</span></label>"
    "<label class='field' style='margin-top:6px'>Seconds per screen</label>"
    "<input type='number' id='mpvsec' min='1' max='120' value='10' step='1' disabled "
    "onchange='mpvAutoRestart()'>"
    "<div class='row' id='mpvrow' style='display:none;margin-top:8px'>"
    "<span class='k'>Screen</span><span class='v' id='mpvname'>--</span></div>"
    "<div class='row' id='mpvrow2' style='display:none'>"
    "<span class='k'>Position</span><span class='v mono' id='mpvidx'>--</span></div>"
    "<div class='row' id='mpvrow3' style='display:none'>"
    "<span class='k'>LED / buzzer</span><span class='v'>"
    "<span id='mpvled' style='display:inline-block;width:11px;height:11px;border-radius:50%;"
    "border:1px solid var(--line);vertical-align:middle;margin-right:6px'></span>"
    "<span id='mpvbuzz' class='mono'>--</span></span></div>"
    "</div>"
    "<div class='card span'><h2>Debug console</h2>"
    "<div class='msg'>Live firmware trace &ndash; NFC tag reads/writes, OctoPrint and "
    "SpoolManagerExtended requests, load-flow steps, menu navigation and scale readings. Kept "
    "in an in-RAM ring buffer of the last 400 lines; older lines are dropped. Off by "
    "default and nothing is recorded while it is off, so switch it on before "
    "reproducing an issue.</div>"
    "<label class='switch'><input type='checkbox' id='dbge' onchange='dbgset(this)'> Enabled</label>"
    "<pre id='dbgbox' style='display:none;margin-top:10px;max-height:300px;overflow:auto;"
    "background:var(--surface2);color:var(--ink);padding:8px;border-radius:6px;font-size:12px;"
    "white-space:pre-wrap;word-break:break-all'></pre></div>"
    "</div></section>"

    "</main>"
    "<p style='text-align:center;color:var(--muted);font-size:.8em;padding:10px'>"
    "OctoScale v" FW_VERSION " &middot; Build " FW_BUILD "</p>"

    "<script>"
    // ---- Tabs + Theme ----
    "function tab(btn,id){document.querySelectorAll('nav button').forEach(function(b){"
    "b.setAttribute('aria-selected',b===btn);});"
    "document.querySelectorAll('.panel').forEach(function(p){p.classList.toggle('active',p.id===id);});}"
    "function gotoTab(id){var b=document.querySelector(\"nav button[onclick*=\\\"'\"+id+\"'\\\"]\");if(b)tab(b,id);}"
    "function toggleTheme(){var r=document.documentElement,cur=r.getAttribute('data-theme');"
    "var dk=window.matchMedia('(prefers-color-scheme:dark)').matches;"
    "r.setAttribute('data-theme',(cur==='dark'||(!cur&&dk))?'light':'dark');}"
    // busy(btn,promise): disables the button during the request, shows '...'.
    "function busy(btn,p){var b=btn&&btn.submitter?btn.submitter:(btn&&btn.target?btn.target:btn);"
    "if(!b||b.tagName!=='BUTTON')return p;var t=b.textContent;b.disabled=true;b.textContent='\\u2026';"
    "var done=function(){b.disabled=false;b.textContent=t;};p.then(done,done);return p;}"
    "function upF(){fetch('/factor').then(r=>r.text()).then(t=>document.getElementById('f').textContent=t);}"
    "function calMethodShow(){var m=document.getElementById('calMethod').value;"
    "document.getElementById('cal1box').style.display=(m==='1')?'':'none';"
    "document.getElementById('cal2box').style.display=(m==='2')?'':'none';}"
    "function cal(){var g=parseFloat(document.getElementById('cw').value);"
    "if(!(g>0)){alert('Enter weight in g');return;}"
    "fetch('/calibrate?weight='+g).then(r=>r.text()).then(t=>{alert('New factor: '+t);upF();});}"
    // 2-point calibration wizard
    "var c2raw1=null,c2raw2=null;"
    "function cal2measure(n){var w=parseFloat(document.getElementById('c2w'+n).value);"
    "if(!(w>0)){alert('Enter the weight in g');return;}"
    "fetch('/calmeasure').then(r=>r.text()).then(t=>{"
    "if(n===1){c2raw1=t;document.getElementById('c2msg1').textContent='Measured. Now place weight B.';"
    "document.getElementById('c2step2').style.display='';}"
    "else{c2raw2=t;document.getElementById('c2msg2').textContent='Measured.';"
    "document.getElementById('c2step3').style.display='';}"
    "}).catch(e=>alert('Request failed: '+e));}"
    "function cal2finish(){if(c2raw1===null||c2raw2===null){alert('Measure both points first');return;}"
    "var w1=document.getElementById('c2w1').value,w2=document.getElementById('c2w2').value;"
    "fetch('/calibrate2?w1='+w1+'&raw1='+c2raw1+'&w2='+w2+'&raw2='+c2raw2)"
    ".then(r=>r.text().then(t=>({ok:r.ok,t:t}))).then(o=>{"
    "document.getElementById('c2msg3').textContent=o.ok?('New factor: '+o.t):o.t;"
    "if(o.ok){upF();c2raw1=null;c2raw2=null;"
    "document.getElementById('c2step2').style.display='none';"
    "document.getElementById('c2step3').style.display='none';"
    "document.getElementById('c2msg1').textContent='';document.getElementById('c2msg2').textContent='';}"
    "}).catch(e=>alert('Request failed: '+e));}"
    // NFC status: the PN5180 reports ready/present/uid under /nfc5180.
    "function upN(){fetch('/nfc5180').then(r=>r.json()).then(o=>{"
    "document.getElementById('uid').textContent=o.present?(o.uid||'?'):'no tag';"
    // ID comes from the flow (the parsed databaseId); shows '--' if no tag/ID.
    "fetch('/flow/status').then(r=>r.json()).then(f=>{"
    "document.getElementById('tag').textContent=(o.present&&f.spoolId>=0)?f.spoolId:'--';});"
    // NFC status chip: green when the reader is ready (matches the display footer),
    // red when not ready. (Tag-present is shown in the NFC tab, not the header chip.)
    "var c=document.getElementById('cNfc').querySelector('.led');"
    "c.className='led '+(o.ready?'ok':'bad');});}"
    // Write the spool ID to the tag (fire-and-poll: /nfcwriteid starts it, /nfcwritestatus reports the result)
    "function nfcwid(){var v=document.getElementById('nid').value;"
    "if(v===''){alert('Enter an ID');return;}"
    "fetch('/nfcwriteid?id='+encodeURIComponent(v)).then(r=>r.text().then(t=>({ok:r.ok,t:t})))"
    ".then(o=>{if(!o.ok){alert(o.t);return;}nfcwpoll();})"
    ".catch(e=>alert('Request failed: '+e));}"
    "function nfcwpoll(){fetch('/nfcwritestatus').then(r=>r.json()).then(s=>{"
    "if(!s.done){setTimeout(nfcwpoll,300);return;}alert(s.msg);})"
    ".catch(e=>alert('Request failed: '+e));}"
    // Erase the tag on the reader (destructive, confirm first) -- shares the same
    // poll/result path as the writes above (/nfcwritestatus reports either kind).
    "function nfcerase(){if(!confirm('Erase all OctoScale data from this tag? "
    "This cannot be undone.'))return;"
    "fetch('/nfcerase',{method:'POST'}).then(r=>r.text().then(t=>({ok:r.ok,t:t})))"
    ".then(o=>{if(!o.ok){alert(o.t);return;}nfcwpoll();})"
    ".catch(e=>alert('Request failed: '+e));}"
    // ---- NFC raw dump (unknown-tag fallback) ----
    "function ndumppoll(){fetch('/nfcdumpstatus').then(r=>r.json()).then(s=>{"
    "if(!s.done){if(s.pending)setTimeout(ndumppoll,400);return;}"
    "document.getElementById('ndumpbtn').disabled=false;"
    "document.getElementById('ndumpbtn').textContent='Create dump';"
    "document.getElementById('ndumpout').style.display='';"
    "var msg=document.getElementById('ndumpmsg');"
    "if(!s.ok){msg.textContent=s.err||'dump failed';msg.style.color='var(--bad)';"
    "document.getElementById('ndumptbl').innerHTML='';return;}"
    "var authFail=(s.blocks||[]).filter(function(b){return!b.authOk;}).length;"
    "msg.textContent=s.blocks.length+' blocks read'+(authFail?', '+authFail+' sector(s) not authenticated (non-default key)':'');"
    "msg.style.color='var(--ok)';"
    "var rows='<tr><th style=\\'text-align:left;padding:2px 8px\\'>Block</th>"
    "<th style=\\'text-align:left;padding:2px 8px\\'>Data (hex)</th>"
    "<th style=\\'text-align:left;padding:2px 8px\\'>ASCII</th></tr>';"
    "(s.blocks||[]).forEach(function(b){"
    "var hex=b.hex||'',ascii='';"
    "if(b.hex){for(var i=0;i<16;i++){var c=parseInt(b.hex.substr(i*2,2),16);"
    "ascii+=(c>=32&&c<127)?String.fromCharCode(c):'.';}}"
    "var status=b.readOk?hex:(b.authOk?'read failed':'auth failed');"
    "rows+='<tr><td style=\\'padding:2px 8px\\'>'+b.block+'</td>"
    "<td style=\\'padding:2px 8px\\'>'+status+'</td>"
    "<td style=\\'padding:2px 8px\\'>'+(b.readOk?ascii:'--')+'</td></tr>';});"
    "document.getElementById('ndumptbl').innerHTML=rows;});}"
    "function nfcdump(){"
    "document.getElementById('ndumpbtn').disabled=true;"
    "document.getElementById('ndumpbtn').textContent='Dumping...';"
    "fetch('/nfcdump',{method:'POST'}).then(r=>r.text().then(t=>({ok:r.ok,t:t})))"
    ".then(o=>{if(!o.ok){alert(o.t);document.getElementById('ndumpbtn').disabled=false;"
    "document.getElementById('ndumpbtn').textContent='Create dump';return;}"
    "setTimeout(ndumppoll,400);})"
    ".catch(e=>{alert('Request failed: '+e);document.getElementById('ndumpbtn').disabled=false;"
    "document.getElementById('ndumpbtn').textContent='Create dump';});}"
    // ---- NFC debug ----
    "function ndbgset(cb){fetch('/nfcdebug?on='+(cb.checked?1:0)).then(r=>r.json()).then(o=>{"
    "document.getElementById('ndbox').style.display=o.debug?'':'none';});}"
    "function ndbg(){fetch('/nfcdebug').then(r=>r.json()).then(o=>{"
    "document.getElementById('ndbg').checked=o.debug;"
    "document.getElementById('ndbox').style.display=o.debug?'':'none';"
    "if(!o.debug)return;"
    "fetch('/nfcprobe').then(r=>r.json()).then(p=>{"
    "document.getElementById('ndtype').textContent=p.present?p.typeName:'no tag';"
    "document.getElementById('nduid').textContent=p.present&&p.uid?p.uid:'--';"
    "var a=p.type===2,v=p.type===1;"
    // No tag present -> p.type is 0 (neither a nor v) and every one of these fields is
    // absent from the JSON, so none of the blocks below would run at all -- the rows
    // would keep showing the PREVIOUS tag's values instead of clearing. Explicitly hide
    // everything first; the a/v blocks below re-show only what applies to this probe.
    "document.getElementById('ndarow').style.display='none';"
    "document.getElementById('ndprow').style.display='none';"
    "document.getElementById('ndvrow').style.display='none';"
    "document.getElementById('ndvirow').style.display='none';"
    "document.getElementById('ndicrow').style.display='none';"
    "if(a){document.getElementById('ndarow').style.display='';"
    "document.getElementById('ndprow').style.display='';"
    "document.getElementById('ndatqa').textContent=p.atqa||'--';"
    "document.getElementById('ndsak').textContent=p.sak||'--';"
    "document.getElementById('ndprod').textContent=p.product||'--';"
    // Page count: fixed by chip variant for Mifare Classic, read via GET_VERSION for
    // NTAG -- either way it's a count of 16 B (Mifare) or 4 B (NTAG) blocks, not the
    // same unit as NFC-V's blockSize x numBlocks below, so shown as a plain count here.
    "if(p.numPages!==undefined){document.getElementById('ndvrow').style.display='';"
    "document.getElementById('ndblk').textContent=p.numPages+' pages/blocks';}}"
    "if(v){document.getElementById('ndvrow').style.display='';"
    "document.getElementById('ndblk').textContent=p.blockSize+' B x '+p.numBlocks;"
    // DSFID/AFI are each optional per-tag (ISO15693 InfoFlags bits) -- only present when
    // the JSON key exists at all (backend omits it entirely if the tag didn't report one).
    "var hasV=p.dsfid!==undefined||p.afi!==undefined;"
    "if(hasV){document.getElementById('ndvirow').style.display='';"
    "document.getElementById('nddsfid').textContent=p.dsfid!==undefined?p.dsfid:'not set';"
    "document.getElementById('ndafi').textContent=p.afi!==undefined?p.afi:'not set';}"
    "if(p.icRef!==undefined){document.getElementById('ndicrow').style.display='';"
    "document.getElementById('ndicref').textContent=p.icRef;}}"
    // NDEF/CC bit: only meaningful for NFC-A/NTAG + NFC-V (Mifare/no-tag -> ccState '').
    // 'ndef' = the tag's one-way OTP bit is set (permanent, survives an erase) -- shown
    // in the warn color as a heads-up, not an error. 'virgin' = never written (ok/green).
    "var cc=p.ccState||'';"
    "document.getElementById('ndccrow').style.display=cc?'':'none';"
    "if(cc){var e=document.getElementById('ndcc');"
    "e.textContent=cc==='ndef'?'Set (NDEF, permanent)':cc==='virgin'?'Not set (virgin)':'Unknown/foreign content';"
    "e.style.color=cc==='ndef'?'var(--warn)':cc==='virgin'?'var(--ok)':'var(--bad)';}"
    // Format/capacity: only meaningful with a tag present.
    "document.getElementById('ndfrow').style.display=p.present?'':'none';"
    "document.getElementById('ndcaprow').style.display=p.present&&p.capacityBytes?'':'none';"
    "if(p.present){document.getElementById('ndfmt').textContent=p.formatLabel||'--';"
    "document.getElementById('ndcap').textContent=(p.capacityBytes||0)+' B';}"
    // Full Extended payload -- only shown when the tag actually carries one. When a
    // tag IS present but carries none, show the unknown-tag dump fallback instead.
    "var ext=p.extended,has=!!p.hasExtendedData;"
    "document.getElementById('ndext').style.display=has?'':'none';"
    "document.getElementById('ndunk').style.display=(p.present&&!has)?'':'none';"
    "if(!p.present||has){document.getElementById('ndumpout').style.display='none';}"
    "if(has&&ext){"
    "var nn=function(v,s){return v===undefined||v===null||v===-1||v===-1.0?'not set':v+(s||'');};"
    // Days-since-epoch (1970-01-01 UTC) -> 'DD.MM.YYYY', same display format
    // SpoolManagerExtended's own UI uses (%d.%m.%Y) -- keeps the two UIs showing the
    // same date instead of OctoScale's raw wire integer next to SpoolManagerExtended's
    // formatted one.
    "var nd=function(v){if(v===undefined||v===null||v<0)return'not set';"
    "var d=new Date(v*86400000);"
    "var p2=function(n){return n<10?'0'+n:''+n;};"
    "return p2(d.getUTCDate())+'.'+p2(d.getUTCMonth()+1)+'.'+d.getUTCFullYear();};"
    "document.getElementById('nedbid').textContent=ext.databaseId>=0?ext.databaseId:'not set';"
    "document.getElementById('nemat').textContent=ext.material||'--';"
    "document.getElementById('nevnd').textContent=ext.vendor||'--';"
    "document.getElementById('necol').textContent=ext.color||'--';"
    "document.getElementById('necoln').textContent=ext.colorName||'--';"
    "document.getElementById('nedia').textContent=nn(ext.diameter,' mm');"
    "document.getElementById('neden').textContent=nn(ext.density,' g/cm3');"
    "document.getElementById('netw').textContent=nn(ext.totalWeight,' g');"
    "document.getElementById('nesw').textContent=nn(ext.spoolWeight,' g');"
    "document.getElementById('neuw').textContent=nn(ext.usedWeight,' g');"
    "document.getElementById('netemp').textContent=nn(ext.temperature,' \\u00b0C');"
    "document.getElementById('nebtemp').textContent=nn(ext.bedTemperature,' \\u00b0C');"
    "document.getElementById('netemp2').textContent=nn(ext.enclosureTemperature,' \\u00b0C');"
    // octoscaleExtended v3 (Mifare Classic 1K only so far). Dates are days-since-epoch
    // on the wire (see HARDWARE.md's v3 section) but rendered as DD.MM.YYYY via nd()
    // above, matching SpoolManagerExtended's own display format (%d.%m.%Y).
    "document.getElementById('nedn').textContent=ext.displayName||'--';"
    "document.getElementById('nerw').textContent=nn(ext.remainingWeight,' g');"
    "document.getElementById('netl').textContent=nn(ext.totalLength,' mm');"
    "document.getElementById('neul').textContent=nn(ext.usedLength,' mm');"
    "document.getElementById('necode').textContent=ext.code||'--';"
    "document.getElementById('nebatch').textContent=ext.batchNumber||'--';"
    "document.getElementById('nefin').textContent=ext.finish||'--';"
    "document.getElementById('nepf').textContent=ext.purchasedFrom||'--';"
    "document.getElementById('nepo').textContent=nd(ext.purchasedOn);"
    "document.getElementById('necost').textContent=nn(ext.cost,' \\u20ac');"
    "document.getElementById('nefu').textContent=nd(ext.firstUse);"
    "document.getElementById('nelu').textContent=nd(ext.lastUse);"
    "var hasTr=ext.temperatureMin>=0&&ext.temperatureMax>=0;"
    "document.getElementById('netrgrow').style.display=hasTr?'':'none';"
    "if(hasTr)document.getElementById('netrg').textContent=ext.temperatureMin+'\\u2013'+ext.temperatureMax+' \\u00b0C';"
    "var hasBtr=ext.bedTemperatureMin>=0&&ext.bedTemperatureMax>=0;"
    "document.getElementById('nebtrgrow').style.display=hasBtr?'':'none';"
    "if(hasBtr)document.getElementById('nebtrg').textContent=ext.bedTemperatureMin+'\\u2013'+ext.bedTemperatureMax+' \\u00b0C';"
    "}"
    // PN5180 chip status (reader hardware, not the tag) -- present only while debug
    // mode is on and the reader is ready (see /nfcprobe's gating on the same).
    "var ch=p.chip;"
    "document.getElementById('ndchipcard').style.display=ch?'':'none';"
    "if(ch){"
    "document.getElementById('ndcdie').textContent=ch.dieId||'--';"
    "document.getElementById('ndceev').textContent=ch.eepromVersion||'--';"
    "var rf=document.getElementById('ndcrf');"
    "rf.textContent=ch.rfFieldOn?'on':'off';"
    "rf.style.color=ch.rfFieldOn?'var(--ok)':'var(--muted)';"
    "document.getElementById('ndcts').textContent=ch.transceiveState||'--';"
    "document.getElementById('ndcsm').textContent=ch.systemMode!==undefined?ch.systemMode:'--';"
    "document.getElementById('ndcss').textContent=ch.systemStatusRaw||'--';"
    "var ot=document.getElementById('ndcot');"
    "ot.textContent=ch.overtempWarning?'YES':'no';"
    "ot.style.color=ch.overtempWarning?'var(--bad)':'var(--ok)';"
    "document.getElementById('ndctc').textContent=ch.tempControlRaw||'--';"
    "document.getElementById('ndcirq').textContent=ch.irqStatusRaw||'--';"
    "}"
    "});});}"
    // ---- Debug console ----
    "var dbgSeq=-1;"
    "function dbgset(cb){fetch('/debuglog?on='+(cb.checked?1:0)).then(r=>r.json()).then(o=>{"
    "document.getElementById('dbgbox').style.display=o.enabled?'':'none';"
    "if(o.enabled)dbgpoll();});}"
    // Self-chaining 500ms poll -- the fastest loop in the page. Stops while the tab is
    // hidden (the visibilitychange handler at the bottom restarts it on return), so a
    // backgrounded tab with the debug console open doesn't keep pulling the log.
    "function dbgpoll(){var cb=document.getElementById('dbge');if(!cb.checked)return;"
    "if(document.hidden)return;"
    "fetch('/debuglog').then(r=>r.json()).then(o=>{"
    "if(o.seq!==dbgSeq){dbgSeq=o.seq;var b=document.getElementById('dbgbox');"
    "b.textContent=o.lines.join('\\n');b.scrollTop=b.scrollHeight;}"
    "setTimeout(dbgpoll,500);});}"
    "function dbgload(){fetch('/debuglog').then(r=>r.json()).then(o=>{"
    "document.getElementById('dbge').checked=o.enabled;"
    "document.getElementById('dbgbox').style.display=o.enabled?'':'none';"
    "if(o.enabled)dbgpoll();});}"
    // ---- Load flow ----
    "var lastState='';"
    // Color CSS matching SpoolManagerExtended (_buildSpoolColorCss / spmSpoolColorCss). Code
    // formats: "rainbow" | "transparent" | "transparent:#hex[;#hex..]" | "#hex[;#hex;#hex]"
    "function spmColorCss(cv){if(!cv)return'';cv=(''+cv).trim();"
    "if(cv.toLowerCase()==='rainbow')return'linear-gradient(135deg,#ff2d2d 0%,#ff9a00 20%,#ffe600 40%,#16c172 60%,#2f7bff 80%,#a044ff 100%)';"
    "var cb='repeating-conic-gradient(#c8c8c8 0% 25%,#ffffff 0% 50%) 50% / 8px 8px';"
    "if(cv.toLowerCase()==='transparent')return cb;"
    "var tr=false;if(cv.toLowerCase().indexOf('transparent:')===0){tr=true;cv=cv.substring(12);}"
    "if(!/^#[0-9a-fA-F]{3,8}(;#[0-9a-fA-F]{3,8}){0,2}$/.test(cv))return'';"
    "var cs=cv.split(';'),st=[],sp=100/cs.length,i;"
    "if(tr){for(i=0;i<cs.length;i++){var t=cs[i].length===7?cs[i]+'8c':cs[i];"
    "st.push(t+' '+(i*sp).toFixed(1)+'%');st.push(t+' '+((i+1)*sp).toFixed(1)+'%');}"
    "return'linear-gradient(135deg,'+st.join(',')+'),'+cb;}"
    "if(cs.length===1)return cs[0];"
    "for(i=0;i<cs.length;i++){st.push(cs[i]+' '+(i*sp).toFixed(1)+'%');st.push(cs[i]+' '+((i+1)*sp).toFixed(1)+'%');}"
    "return'linear-gradient(135deg,'+st.join(',')+')';}"
    // Spool info card: row1 left vendor/material, right color tile+name;
    //                  row2 left 'remaining', right the remaining weight.
    "function spoolCard(o){var css=spmColorCss(o.color);"
    "var sw=css?('<span class=\"swatch\" style=\"background:'+css+'\"></span>'):'';"
    "var cn=o.colorName||'';"
    "var vend=o.vendor||'\\u2013';var mat=o.material||'\\u2013';"
    "var rem=(o.remaining>=0)?(o.remaining.toFixed(0)+' g'):'\\u2013';"
    "return'<div class=\"spoolcard\">'"
    "+'<div class=\"sc-tl\"><div class=\"sc-vend\">'+vend+'</div><div class=\"sc-mat\">'+mat+'</div></div>'"
    "+'<div class=\"sc-tr\">'+sw+'<span class=\"sc-cn\">'+cn+'</span></div>'"
    "+'<div class=\"sc-bl\">remaining</div>'"
    "+'<div class=\"sc-br\">'+rem+'</div>'"
    "+'</div>';}"
    "function fRender(o){var fl=document.getElementById('flowcard'),b=document.getElementById('fbody'),"
    "cb=document.getElementById('fcancel'),h=document.getElementById('fh');"
    "if(o.state==='idle'){fl.style.display='none';return;}"
    "fl.style.display='block';cb.style.display=(o.state==='done'||o.state==='idle')?'none':'block';"
    // Countdown bar: only when a timeout is set. Tag present (askRemainMs<0) -> full; else shrinks.
    "var tb=document.getElementById('ftbar'),tf=document.getElementById('ftfill');"
    "if(o.askTimeoutSec>0){tb.style.display='block';"
    "if(o.askRemainMs<0){tf.style.width='100%';tf.style.background='var(--accent)';}"
    "else{var pc=Math.max(0,Math.min(100,o.askRemainMs/(o.askTimeoutSec*10)));"
    "tf.style.width=pc+'%';tf.style.background=pc<30?'var(--bad)':'var(--accent)';}}"
    "else{tb.style.display='none';}"
    "var s='<div class=\"row\"><span class=\"k\">Spool ID</span><span class=\"v mono\">'+o.spoolId+'</span></div>';"
    "if(o.state==='db_check'){h.textContent='Checking database\\u2026';b.innerHTML=s;return;}"
    "if(o.state==='unknown'){h.textContent='Unknown spool';b.innerHTML=s+'<div class=\"msg bad\" style=\"margin-top:10px\">'+(o.msg||'not in DB')+'</div>';return;}"
    // Spool is known -> load it or record a new weight.
    "if(o.state==='ask_action'){h.textContent='What to do?';"
    "s+='<div class=\"row\"><span class=\"k\">Spool</span><span class=\"v\">'+(o.spoolName||'?')+'</span></div>';"
    "s+=spoolCard(o);"
    "s+='<button class=\"primary\" onclick=\"fact(event,\\'load\\')\">Load into printer</button>';"
    "s+=o.canWeigh?'<button class=\"ghost\" onclick=\"fact(event,\\'weigh\\')\">Save weight</button>':"
    "'<div class=\"note\">Weighing not possible: no empty/total weight in the DB</div>';"
    "b.innerHTML=s;return;}"
    // Confirmation step: grossWeight = the LIVE scale reading.
    "if(o.state==='weigh_confirm'){h.textContent='Place spool on scale';"
    "var rest=o.grossWeight-o.spoolWeight;if(rest<0)rest=0;if(rest>o.totalWeight)rest=o.totalWeight;"
    "s+='<div class=\"row\"><span class=\"k\">Spool</span><span class=\"v\">'+(o.spoolName||'?')+'</span></div>';"
    "s+='<div class=\"row\"><span class=\"k\">Scale gross</span><span class=\"v mono\">'+o.grossWeight.toFixed(1)+' g</span></div>';"
    "s+='<div class=\"row\"><span class=\"k\">- Empty weight</span><span class=\"v mono\">'+o.spoolWeight.toFixed(1)+' g</span></div>';"
    "s+='<div class=\"row\"><span class=\"k\">Remaining</span><span class=\"v mono\">'+rest.toFixed(1)+' / '+o.totalWeight.toFixed(1)+' g</span></div>';"
    "s+='<button class=\"primary\" onclick=\"fweigh(event)\">Save</button>';"
    "b.innerHTML=s;return;}"
    "if(o.state==='weighing'){h.textContent='Saving\\u2026';b.innerHTML=s;return;}"
    "if(o.state==='ask_printer'){h.textContent='Load into which printer?';"
    "s+='<div class=\"row\"><span class=\"k\">Spool</span><span class=\"v\">'+(o.spoolName||'?')+'</span></div>';"
    "(o.printers||[]).forEach(function(p){s+='<button class=\"ghost\" onclick=\"fpr(event,'+p.idx+')\">'+p.name+'</button>';});"
    "b.innerHTML=s;return;}"
    "if(o.state==='ask_tool'){h.textContent='Into which tool?';"
    "s+='<div class=\"row\"><span class=\"k\">Spool</span><span class=\"v\">'+(o.spoolName||'?')+'</span></div>';"
    "for(var i=0;i<o.toolCount;i++)s+='<button class=\"ghost\" onclick=\"ftool(event,'+i+')\">Tool '+i+'</button>';"
    "b.innerHTML=s;return;}"
    "if(o.state==='loading'){h.textContent='Loading\\u2026';b.innerHTML=s;return;}"
    "if(o.state==='done'){var wg=o.tool<0;h.textContent=wg?'Saved \\u2713':'Loaded \\u2713';"
    "b.innerHTML=s+'<div class=\"msg ok\" style=\"margin-top:10px\">'+(wg?(o.msg||'Weight saved'):('Loaded into tool '+o.tool))+'</div>';"
    "setTimeout(fcancel,4000);return;}"
    "if(o.state==='error'){h.textContent='Error';b.innerHTML=s+'<div class=\"msg bad\" style=\"margin-top:10px\">'+(o.msg||'Error')+'</div>';return;}}"
    // fpoll: on idle -> active transition, jump to the Operate tab automatically.
    "function fpoll(){fetch('/flow/status').then(r=>r.json()).then(o=>{"
    "if(lastState==='idle'&&o.state!=='idle')gotoTab('betrieb');"
    "lastState=o.state;fRender(o);});}"
    "function fact(e,w){busy(e,fetch('/flow/action?do='+w).then(r=>r.json()).then(fRender));}"
    "function fweigh(e){busy(e,fetch('/flow/weigh').then(r=>r.json()).then(fRender));}"
    "function frw(e){busy(e,fetch('/flow/reweigh').then(r=>r.json()).then(fRender));}"
    "function fpr(e,i){busy(e,fetch('/flow/printer?idx='+i).then(r=>r.json()).then(fRender));}"
    "function ftool(e,n){busy(e,fetch('/flow/tool?n='+n).then(r=>r.json()).then(fRender));}"
    "function fcancel(){fetch('/flow/cancel').then(r=>r.json()).then(fRender);}"
    // ---- Firmware update from URL ----
    "function fwurl(e){var u=document.getElementById('fwu').value.trim();"
    "var m=document.getElementById('fwmsg');"
    "if(!u){m.style.color='var(--bad)';m.textContent='\\u2717 Enter a URL';return;}"
    "if(!confirm('Download and flash firmware from this URL? The device reboots afterwards.'))return;"
    "m.style.color='var(--muted)';m.textContent='Downloading & flashing\\u2026 (may take a while, do not reload)';"
    "busy(e,fetch('/updateurl?url='+encodeURIComponent(u),{method:'POST'}).then(r=>"
    "r.text().then(t=>{if(r.ok){m.style.color='var(--ok)';m.textContent='\\u2713 '+t+' \\u2013 page reloads shortly';"
    "setTimeout(function(){location.href='/';},9000);}"
    "else{m.style.color='var(--bad)';m.textContent='\\u2717 '+t;}}))"
    ".catch(()=>{m.style.color='var(--muted)';m.textContent='Connection lost \\u2013 the device may still be flashing, reload shortly';"
    "setTimeout(function(){location.href='/';},12000);}));}"
    // ---- Selection timeout ----
    // Backlight slider live (throttled) + saves all three values to NVS.
    "var _blt=0;"
    "function blset(v){document.getElementById('blval').textContent=v;"
    "var now=Date.now();if(now-_blt<120)return;_blt=now;fetch('/backlight?level='+v);}"
    "function blsave(){var a=document.getElementById('blv').value,"
    "d=document.getElementById('bld').value,t=document.getElementById('blt').value,"
    "se=document.getElementById('sse').checked?1:0,st=document.getElementById('sst').value;"
    "var m=document.getElementById('blmsg');"
    "fetch('/display?active='+a+'&dim='+d+'&timeout='+t+'&ssEnabled='+se+'&ssTimeout='+st)"
    ".then(r=>r.json()).then(function(){"
    "m.textContent='\\u2713 saved';m.style.color='var(--ok)';"
    "setTimeout(()=>m.textContent='',2000);});}"
    "function blload(){fetch('/display').then(r=>r.json()).then(o=>{"
    "document.getElementById('blv').value=o.active;document.getElementById('blval').textContent=o.active;"
    "document.getElementById('bld').value=o.dim;document.getElementById('bldval').textContent=o.dim;"
    "document.getElementById('blt').value=o.timeout;"
    "document.getElementById('sse').checked=!!o.ssEnabled;"
    "document.getElementById('sst').value=o.ssTimeout;});}"
    // ---- Buzzer ----
    "function bzsave(){var e=document.getElementById('bze').checked?1:0,"
    "m=document.getElementById('bzm').value,v=document.getElementById('bzv').value,"
    "f=document.getElementById('bzf').value,mo=document.getElementById('bzmsg');"
    "fetch('/buzzer?enabled='+e+'&mode='+m+'&vol='+v+'&freq='+f).then(r=>r.json()).then(function(){"
    "mo.textContent='\\u2713 saved';mo.style.color='var(--ok)';setTimeout(()=>mo.textContent='',2000);});}"
    "function bztest(ev){ev.preventDefault();fetch('/buzzer?test=1');}"
    "function bzload(){fetch('/buzzer').then(r=>r.json()).then(o=>{"
    "document.getElementById('bze').checked=!!o.enabled;"
    "document.getElementById('bzm').value=o.mode;"
    "document.getElementById('bzv').value=o.vol;document.getElementById('bzvval').textContent=o.vol;"
    "document.getElementById('bzf').value=o.freq;});}"
    // ---- TFT screen preview ----
    "var mpvTimer=null,mpvAutoTimer=null;"
    "function mpvApply(o){"
    "document.getElementById('mpv').checked=o.active;"
    "document.getElementById('mpvauto').disabled=!o.active;"
    "document.getElementById('mpvsec').disabled=!o.active;"
    // The device itself stopping the preview (knob press) must also stop auto-cycling
    // here -- otherwise this keeps POSTing ?next=1 into a preview that's no longer
    // running (harmless server-side, since /menupreview ignores next when inactive,
    // but the checkbox would keep showing 'on' for a feature doing nothing).
    "if(!o.active&&document.getElementById('mpvauto').checked){"
    "document.getElementById('mpvauto').checked=false;clearInterval(mpvAutoTimer);mpvAutoTimer=null;}"
    "document.getElementById('mpvrow').style.display=o.active?'':'none';"
    "document.getElementById('mpvrow2').style.display=o.active?'':'none';"
    "document.getElementById('mpvrow3').style.display=o.active?'':'none';"
    "if(o.active){document.getElementById('mpvname').textContent=o.name||'--';"
    "document.getElementById('mpvidx').textContent=(o.index+1)+' / '+o.count;"
    "var led=document.getElementById('mpvled');"
    "led.style.background=o.led||'transparent';"
    "led.style.boxShadow=o.led?('0 0 6px 1px '+o.led):'none';"
    "document.getElementById('mpvbuzz').textContent=o.buzzing?'\\u266a sounding':'silent';}}"
    // Polls at 300ms while active -- fast enough that a 1.5s LED flash or a 90ms buzzer
    // blip is actually visible in the web UI instead of always landing between polls.
    "function mpvpoll(){fetch('/menupreview').then(r=>r.json()).then(o=>{"
    "mpvApply(o);"
    // Self-chaining poll while active (mirrors dbgpoll) -- picks up the device-side
    // stop (knob press) so the web UI switch doesn't lie about the real state.
    "if(o.active&&!document.hidden){mpvTimer=setTimeout(mpvpoll,300);}});}"
    "function mpvset(cb){var on=cb.checked?1:0;"
    "fetch('/menupreview?on='+on).then(r=>r.json()).then(o=>{mpvApply(o);"
    "if(o.active){clearTimeout(mpvTimer);mpvpoll();}});}"
    // Auto-cycle: a plain client-side setInterval calling the existing ?next=1 step
    // endpoint -- no new firmware endpoint needed, this just automates the same knob
    // action a person would do by hand.
    "function mpvAutoToggle(){"
    "var cb=document.getElementById('mpvauto');"
    "clearInterval(mpvAutoTimer);mpvAutoTimer=null;"
    "if(cb.checked){"
    "var sec=Math.max(1,parseInt(document.getElementById('mpvsec').value,10)||10);"
    "mpvAutoTimer=setInterval(function(){fetch('/menupreview?next=1');},sec*1000);"
    "}}"
    // Changing the seconds field while auto-cycle is running restarts the interval at
    // the new period instead of waiting out whatever was left of the old one.
    "function mpvAutoRestart(){if(document.getElementById('mpvauto').checked)mpvAutoToggle();}"
    "function tmload(){fetch('/flow/timeout').then(r=>r.json()).then(o=>{"
    "document.getElementById('tmsec').value=o.sec;});}"
    "function tmset(e){var v=document.getElementById('tmsec').value;if(v==='')return;"
    "var m=document.getElementById('tmmsg');"
    "busy(e,fetch('/flow/timeout?sec='+v).then(r=>r.json()).then(o=>{"
    "m.textContent='\\u2713 '+(o.sec==0?'never':o.sec+' s');m.style.color='var(--ok)';"
    "setTimeout(()=>m.textContent='',3000);}));}"
    // ---- OctoPrint instances ----
    "function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){"
    "return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}"
    "function octol(){fetch('/octoprint/list').then(r=>r.json()).then(a=>{"
    "if(!a.length){document.getElementById('octobox').innerHTML="
    "'<div class=\"note\">No printers configured.</div>';return;}"
    "var h='';a.forEach(function(p){"
    "var db=p.dbId?('&#x1F5C4;&#xFE0F; '+esc(p.dbId)):'&#x1F4BE; local (SQLite)';"
    "var key=p.hasKey?'<span title=\"API key set\">&#x1F511;</span>':"
    "'<span title=\"no API key\" style=\"color:var(--bad)\">&#x26A0;&#xFE0F;</span>';"
    "h+='<div class=\"pcard\">'"
    "+'<div class=\"top\"><span class=\"dot\" id=\"od'+p.idx+'\"></span>'"
    "+'<span class=\"nm\">'+esc(p.name||'(unnamed)')+'</span>'+key+'</div>'"
    "+'<div class=\"addr mono\">'+esc(p.host)+':'+p.port+'</div>'"
    "+'<div class=\"db\">'+db+'</div>'"
    "+'<div class=\"pst\" id=\"ot'+p.idx+'\">&nbsp;</div>'"
    "+'<div class=\"act\">'"
    "+'<button onclick=\"octot(event,'+p.idx+')\">Test connection</button>'"
    "+'<button onclick=\"octoe('+p.idx+')\">Edit</button>'"
    "+'<button class=\"del\" onclick=\"octod('+p.idx+')\">Delete</button>'"
    "+'</div>'"
    // Hidden by default; octoe() toggles it. Prefilled with the current name/host/
    // port -- apikey is deliberately left blank (the server never sends the real key
    // back, see octoUpdate's comment), with a placeholder saying so.
    "+'<div class=\"edit\" id=\"oe'+p.idx+'\" style=\"display:none\">'"
    "+'<input type=\"text\" id=\"oen'+p.idx+'\" value=\"'+esc(p.name)+'\" placeholder=\"Name\">'"
    "+'<input type=\"text\" id=\"oeh'+p.idx+'\" value=\"'+esc(p.host)+'\" placeholder=\"IP / hostname\">'"
    "+'<input type=\"number\" id=\"oep'+p.idx+'\" value=\"'+p.port+'\" placeholder=\"Port\">'"
    "+'<input type=\"text\" id=\"oek'+p.idx+'\" placeholder=\"'+(p.hasKey?'API key (unchanged)':'API key')+'\">'"
    "+'<div class=\"act\">'"
    "+'<button class=\"primary\" onclick=\"octosave('+p.idx+')\">Save</button>'"
    "+'<button onclick=\"octoe('+p.idx+')\">Cancel</button>'"
    "+'</div></div></div>';});"
    "document.getElementById('octobox').innerHTML=h;});}"
    "function octot(e,i){var st=document.getElementById('ot'+i),d=document.getElementById('od'+i);"
    "st.textContent='testing\\u2026';st.style.color='var(--muted)';if(d)d.className='dot wait';"
    "busy(e,fetch('/octoprint/test?idx='+i).then(r=>r.json()).then(o=>{"
    "if(o.toolCount>0){st.textContent='\\u2713 connected, '+o.toolCount+' tool(s)';st.style.color='var(--ok)';if(d)d.className='dot ok';}"
    "else{st.textContent='\\u2717 '+(o.error||'Error');st.style.color='var(--bad)';if(d)d.className='dot err';}}));}"
    "function octoadd(){var b=new URLSearchParams();"
    "b.set('name',document.getElementById('oname').value);"
    "b.set('host',document.getElementById('ohost').value);"
    "b.set('port',document.getElementById('oport').value);"
    "b.set('apikey',document.getElementById('okey').value);"
    "if(!document.getElementById('ohost').value){alert('Host required');return;}"
    "fetch('/octoprint/add',{method:'POST',body:b}).then(r=>r.text().then(t=>({ok:r.ok,t:t})))"
    ".then(o=>{if(!o.ok)alert(o.t);else{document.getElementById('oname').value='';"
    "document.getElementById('ohost').value='';document.getElementById('okey').value='';"
    "octol();dbload();}});}"
    "function octoe(i){var d=document.getElementById('oe'+i);"
    "d.style.display=d.style.display==='none'?'':'none';}"
    "function octosave(i){var b=new URLSearchParams();"
    "b.set('idx',i);"
    "b.set('name',document.getElementById('oen'+i).value);"
    "b.set('host',document.getElementById('oeh'+i).value);"
    "b.set('port',document.getElementById('oep'+i).value);"
    "if(!document.getElementById('oeh'+i).value){alert('Host required');return;}"
    "var key=document.getElementById('oek'+i).value;"
    "if(key!=='')b.set('apikey',key);"
    "fetch('/octoprint/edit',{method:'POST',body:b}).then(r=>r.text().then(t=>({ok:r.ok,t:t})))"
    ".then(o=>{if(!o.ok)alert(o.t);else{octol();dbload();}});}"
    "function octod(i){if(confirm('Delete printer?'))fetch('/octoprint/del?idx='+i).then(function(){octol();dbload();});}"
    "function dbrefresh(e){busy(e,fetch('/octoprint/refreshdb').then(r=>r.json()).then(function(){octol();dbload();}));}"
    // ---- DB source ----
    "function dbload(){Promise.all([fetch('/db/get').then(r=>r.json()),"
    "fetch('/octoprint/list').then(r=>r.json())]).then(function(a){"
    "var cfg=a[0],list=a[1],sel=document.getElementById('dbsel');"
    "if(!list.length){sel.innerHTML='<option>No printers configured</option>';return;}"
    "sel.innerHTML=list.map(function(p){return '<option value=\"'+p.idx+'\"'"
    "+(p.idx===cfg.dbInstance?' selected':'')+'>'+p.name+' ('+p.host+':'+p.port+')</option>';}).join('');});}"
    "function dbset(){var i=document.getElementById('dbsel').value;fetch('/db/set?idx='+i);}"
    "function dbtest(e){var m=document.getElementById('mtestmsg');"
    "var v=document.getElementById('dbtid').value.trim();"
    "var go=function(id){m.textContent='Testing id='+id+'\\u2026';m.style.color='var(--muted)';"
    "busy(e,fetch('/db/test?id='+encodeURIComponent(id)).then(r=>r.json()).then(o=>{"
    "if(o.error){m.textContent='\\u2717 '+o.error;m.style.color='var(--bad)';}"
    "else if(o.found){m.textContent='\\u2713 Spool '+id+': '+(o.name||'(no name)');m.style.color='var(--ok)';}"
    "else{m.textContent='\\u2713 Connected (spool '+id+' not in DB)';m.style.color='var(--ok)';}}));};"
    "if(v!==''){go(v);return;}"
    "m.textContent='Reading tag\\u2026';m.style.color='var(--muted)';"
    // The tag's ID comes from the flow (the parsed databaseId, PN5180).
    "fetch('/flow/status').then(r=>r.json()).then(o=>{"
    "if(o.spoolId>=0){go(o.spoolId);}"
    "else{m.textContent='\\u2717 No tag with an ID present - enter one';m.style.color='var(--bad)';}});}"
    // ---- Backup / restore ----
    "function bkexport(e){var pw=document.getElementById('bkpw').value;"
    "var m=document.getElementById('bkmsg');m.style.color='var(--muted)';m.textContent='Creating backup\\u2026';"
    "busy(e,fetch('/backup?pw='+encodeURIComponent(pw)).then(r=>r.text()).then(t=>{"
    "var a=document.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(t);"
    "a.download='octoscale-backup.json';document.body.appendChild(a);a.click();a.remove();"
    "m.style.color='var(--ok)';m.textContent='\\u2713 Backup downloaded'+(pw?' (keys encrypted)':' (without API keys)');"
    "}).catch(()=>{m.style.color='var(--bad)';m.textContent='\\u2717 Export failed';}));}"
    "function bkimport(e){var f=document.getElementById('bkfile').files[0];"
    "var m=document.getElementById('bkmsg');"
    "if(!f){m.style.color='var(--bad)';m.textContent='\\u2717 Choose a backup file first';return;}"
    "if(!confirm('Restore config from backup? Overwrites all current printers/settings.'))return;"
    "var pw=document.getElementById('bkpw').value;var rd=new FileReader();"
    "rd.onload=function(){m.style.color='var(--muted)';m.textContent='Restoring\\u2026';"
    "busy(e,fetch('/restore?pw='+encodeURIComponent(pw),{method:'POST',headers:{'Content-Type':'text/plain'},body:rd.result}).then(r=>"
    "r.text().then(t=>{if(!r.ok){m.style.color='var(--bad)';m.textContent='\\u2717 '+t;return;}"
    "m.style.color='var(--ok)';m.textContent='\\u2713 Restored \\u2013 reload the page';"
    "octol();dbload();})));};rd.readAsText(f);}"
    // ---- System metrics ----
    "function kb(n){return (n/1024).toFixed(1)+' KB';}"
    "function pgrow(lab,used,tot){var pct=tot?Math.round(used*100/tot):0;"
    "var col=pct>=90?'var(--bad)':pct>=70?'var(--warn)':'var(--ok)';"
    "return '<div style=\"margin:9px 0;padding:0\"><div style=\"display:flex;justify-content:space-between;"
    "padding:0;font-size:.85em\"><span>'+lab+'</span><span class=\"mono\">'+kb(used)+' / '+kb(tot)+' ('+pct+'%)</span></div>"
    "<div class=\"bar\" style=\"margin-top:3px\"><i style=\"width:'+pct+'%;background:'+col+'\"></i></div></div>';}"
    "function upt(s){var d=Math.floor(s/86400),h=Math.floor(s%86400/3600),"
    "m=Math.floor(s%3600/60);return (d?d+'d ':'')+(h?h+'h ':'')+m+'m';}"
    "function pctbar(lab,pct){pct=Math.max(0,Math.min(100,pct));"
    "var col=pct>=90?'var(--bad)':pct>=70?'var(--warn)':'var(--ok)';"
    "return '<div style=\"margin:7px 0;padding:0\"><div style=\"display:flex;justify-content:space-between;"
    "padding:0;font-size:.85em\"><span>'+lab+'</span><span class=\"mono\">'+pct+'%</span></div>"
    "<div class=\"bar\" style=\"margin-top:3px\"><i style=\"width:'+pct+'%;background:'+col+'\"></i></div></div>';}"
    "function rrn(n){return {0:'Unknown',1:'Power-On',2:'External Pin',3:'Software',"
    "4:'Panic/Exception',5:'Interrupt-WDT',6:'Task-WDT',7:'Other-WDT',8:'Deep-Sleep',"
    "9:'Brownout',10:'SDIO'}[n]||('Code '+n);}"
    // resets worth flagging red: anything that isn't a normal power-on or a
    // deliberate software/OTA restart -- brownout, panic, and both watchdog kinds.
    "function rrbad(n){return n===4||n===5||n===6||n===7||n===9;}"
    "function sysupd(){fetch('/system').then(r=>r.json()).then(o=>{"
    // header status chips: Scale (ready) + DB (reachable). NFC via upN, WiFi via wifiupd.
    "document.getElementById('cScale').querySelector('.led').className='led '+(o.scaleReady?'ok':'bad');"
    "document.getElementById('cDb').querySelector('.led').className='led '+(o.dbReachable===1?'ok':(o.dbReachable===0?'bad':''));"
    "var h='<div style=\"font-size:.9em;margin-bottom:8px\"><b>'+(o.chipModel||'ESP32')+'</b> "
    "rev '+o.chipRev+' \\u00b7 '+o.chipCores+' Core'+(o.chipCores>1?'s':'')+' @ '+o.cpuFreqMhz+' MHz</div>';"
    "h+=pgrow('RAM (Heap)',o.heapUsed,o.heapTotal);"
    "if(o.psramTotal>0)h+=pgrow('PSRAM',o.psramTotal-o.psramFree,o.psramTotal);"
    "h+=pgrow('Flash (Sketch)',o.sketchUsed,o.sketchTotal);"
    "if(o.core0Load>=0){h+=pctbar('CPU Core 0',o.core0Load)+pctbar('CPU Core 1',o.core1Load);}"
    "else{h+=pctbar('CPU-Last (~loop)',o.cpuLoad);}"
    "h+='<div style=\"font-size:.85em;margin-top:8px\">'"
    "+'<div class=\"row\"><span class=\"k\">Temp</span><span class=\"v mono\">'+o.temp.toFixed(1)+' \\u00b0C</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">Heap min. free</span><span class=\"v mono\">'+kb(o.heapMinFree)+'</span></div>'"
    "+(o.psramMinFree?'<div class=\"row\"><span class=\"k\">PSRAM min. free</span><span class=\"v mono\">'+kb(o.psramMinFree)+'</span></div>':'')"
    "+'<div class=\"row\"><span class=\"k\">Flash chip</span><span class=\"v mono\">'+kb(o.flashChip)+(o.flashSpeedMhz?' @ '+o.flashSpeedMhz+' MHz':'')+'</span></div>'"
    "+(o.otaPartSize?'<div class=\"row\"><span class=\"k\">OTA partition</span><span class=\"v mono\">'+kb(o.otaPartSize)+'</span></div>':'')"
    "+'<div class=\"row\"><span class=\"k\">Tasks</span><span class=\"v mono\">'+o.taskCount+'</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">Last reset</span><span class=\"v\" style=\"color:'+(rrbad(o.resetReason)?'#e55':'inherit')+'\">'+rrn(o.resetReason)+'</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">SDK</span><span class=\"v mono\">'+(o.sdkVersion||'?')+'</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">Uptime</span><span class=\"v mono\">'+upt(o.uptimeSec)+'</span></div></div>';"
    "document.getElementById('sysbox').innerHTML=h;});}"
    // ---- WiFi status ----
    "function wifibars(q){var n=q>=75?4:q>=50?3:q>=25?2:q>0?1:0;"
    "var col=q>=50?'var(--ok)':q>=25?'var(--warn)':'var(--bad)';var s='';"
    "for(var i=1;i<=4;i++)s+='<span style=\"display:inline-block;width:4px;margin-right:1px;"
    "height:'+(i*3+2)+'px;background:'+(i<=n?col:'var(--line)')+'\"></span>';return s;}"
    "function wifiupd(){fetch('/wifi/status').then(r=>r.json()).then(o=>{"
    "var box=document.getElementById('wifibox');"
    "box.innerHTML='<div class=\"row\"><span class=\"k\">SSID</span><span class=\"v\">'+(o.ssid||'--')+'</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">Signal</span><span class=\"v\">'+(o.connected?wifibars(o.quality)+' '+o.quality+'% ('+o.rssi+' dBm)':'not connected')+'</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">IP</span><span class=\"v mono\">'+o.ip+'</span></div>'"
    "+'<div class=\"row\"><span class=\"k\">Host</span><span class=\"v mono\">'+o.host+'.local</span></div>'"
    "+(o.connected&&o.channel?'<div class=\"row\"><span class=\"k\">Channel</span><span class=\"v mono\">'+o.channel+(o.bssid?' \\u00b7 '+o.bssid:'')+'</span></div>':'')"
    "+'<div class=\"row\"><span class=\"k\">MAC</span><span class=\"v mono\">'+o.mac+'</span></div>';"
    // WiFi status chip (SSID + connected color)
    "var cw=document.getElementById('cWifi');cw.querySelector('.led').className='led '+(o.connected?'ok':'bad');"
    "cw.querySelector('b').textContent=o.ssid||'--';});}"
    "function wifiportal(e){if(!confirm('Reconfigure WiFi? The device reboots and "
    "opens the setup network \"OctoScale-Setup\". It is briefly unreachable afterwards.'))return;"
    "busy(e,fetch('/wifi/portal').then(r=>r.text()).then(function(){"
    "document.body.innerHTML='<div style=\"max-width:400px;margin:40px auto;padding:20px;"
    "font-family:verdana;background:var(--surface);border-left:3px solid var(--accent);border-radius:.3rem\">"
    "<b>WiFi setup started.</b><br/><br/>Connect to the network "
    "<b>\"OctoScale-Setup\"</b> and choose your WiFi.</div>';}));}"
    // ---- Poll loop + init ----
    // All periodic polls go through pv(): a hidden tab (minimized, other tab in
    // front) skips its fetch entirely instead of hammering the ESP with ~8 req/s
    // for a page nobody is looking at. The device shrugs that load off (both cores
    // idle well under 15%), but it's pointless WiFi traffic and airtime. Coming back
    // to the tab fires one immediate refresh so the page is current right away
    // rather than showing stale values until the next interval elapses.
    "function pv(f){return function(){if(!document.hidden)f();};}"
    "function wpoll(){fetch('/weight').then(r=>r.text())"
    ".then(t=>document.getElementById('w').textContent=t);}"
    // ---- HX711 diagnostics (Scale tab) ----
    "function scpoll(){fetch('/scaleinfo').then(r=>r.json()).then(s=>{"
    "var rd=document.getElementById('scready');"
    "rd.textContent=s.hxReady?'yes':'no';"
    "rd.style.color=s.hxReady?'var(--ok)':'var(--bad)';"
    "document.getElementById('scage').textContent=s.lastReadAgoMs>=0?(s.lastReadAgoMs+' ms ago'):'never';"
    "document.getElementById('scraw').textContent=s.raw;"
    "document.getElementById('scoff').textContent=s.offset;"
    "document.getElementById('scfac').textContent=Number(s.scaleFactor).toFixed(4);"
    "document.getElementById('scnoise').textContent=s.noiseStdDev===null?'--- (warming up)':"
    "(Number(s.noiseStdDev).toFixed(1)+' counts ('+s.noiseSamples+' samples)');"
    "});}"
    "setInterval(pv(wpoll),500);"
    "setInterval(pv(upN),700);setInterval(pv(fpoll),800);setInterval(pv(wifiupd),5000);"
    "setInterval(pv(sysupd),3000);setInterval(pv(ndbg),700);setInterval(pv(scpoll),1000);"
    "document.addEventListener('visibilitychange',function(){if(!document.hidden){"
    "wpoll();upN();fpoll();wifiupd();sysupd();ndbg();scpoll();"
    // dbgpoll's setTimeout chain stops itself while hidden (see dbgpoll) -> restart it.
    "var cb=document.getElementById('dbge');if(cb&&cb.checked)dbgpoll();}});"
    "upF();upN();fpoll();octol();dbload();wifiupd();sysupd();tmload();ndbg();blload();bzload();dbgload();mpvpoll();</script>"
    "</body></html>";
